---
extends: airbnb
parser: babel-eslint
env:
  browser: true
  node: true
rules:
  no-underscore-dangle: 0
  no-plusplus: 0
  no-multi-assign: 0
  no-nested-ternary: 0
  no-unneeded-ternary: 0
  no-param-reassign: 0
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  max-len:
    - error
    - ignoreComments: true
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
  no-await-in-loop: 0
  function-paren-newline: 0
  indent: 0
  prefer-destructuring: 0
  react/prop-types: 0
  react/no-multi-comp: 0
  react/sort-comp: 0
  react/jsx-key: 1
  react/jsx-indent: 0
  jsx-a11y/anchor-is-valid: 0
  class-methods-use-this: 0
  object-curly-newline: 0